version: "3.7"

services:
  nginx-react:
    container_name: appdev_analytics_react
    image: ghcr.io/whoigit/appdev-analytics-frontend-client:stable
    ports:
      - 3000:80
    environment:
      NODE_ENV: production
    # add this compose file to the Traefik reverse proxy network
    labels:
      - "traefik.http.routers.nginx-react.rule=Host(`appdev-analytics.whoi.edu`)"
      - "traefik.http.routers.nginx-react.tls=true"

networks:
  default:
    external:
      name: proxy-network
