version: "3.7"

services:
  nginx-react:
    container_name: appdev_analytics_react
    image: ghcr.io/whoigit/appdev-analytics-frontend-client:stable
    ports:
      - 3000:80
    environment:
      NODE_ENV: production
